// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_0SPJ131uxXKe7Ts8Epsp927sJ6sBsKc',
    appId: '1:218878146050:web:fa21f80dde04b59080191b',
    messagingSenderId: '218878146050',
    projectId: 'dermaly-65610',
    authDomain: 'dermaly-65610.firebaseapp.com',
    storageBucket: 'dermaly-65610.firebasestorage.app',
    measurementId: 'G-V2Y8LD88JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHqS8t5qiD5Y9PjD-Ll5sDNGrf461DORg',
    appId: '1:218878146050:android:b34ccd93109f537d80191b',
    messagingSenderId: '218878146050',
    projectId: 'dermaly-65610',
    storageBucket: 'dermaly-65610.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjqa_o6cryFDmz-05qVYWV5Z4kSeBk6FA',
    appId: '1:218878146050:ios:9879d649fdc1079c80191b',
    messagingSenderId: '218878146050',
    projectId: 'dermaly-65610',
    storageBucket: 'dermaly-65610.firebasestorage.app',
    iosBundleId: 'com.example.ziskin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjqa_o6cryFDmz-05qVYWV5Z4kSeBk6FA',
    appId: '1:218878146050:ios:9879d649fdc1079c80191b',
    messagingSenderId: '218878146050',
    projectId: 'dermaly-65610',
    storageBucket: 'dermaly-65610.firebasestorage.app',
    iosBundleId: 'com.example.ziskin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_0SPJ131uxXKe7Ts8Epsp927sJ6sBsKc',
    appId: '1:218878146050:web:3bc9320667fefd0580191b',
    messagingSenderId: '218878146050',
    projectId: 'dermaly-65610',
    authDomain: 'dermaly-65610.firebaseapp.com',
    storageBucket: 'dermaly-65610.firebasestorage.app',
    measurementId: 'G-9CF209H6VE',
  );
}
